DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER (
    ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    TOTAL_LOAN DOUBLE NOT NULL,
    INTEREST DOUBLE NOT NULL,
    YEARS INTEGER NOT NULL
);
